services:
  - type: web
    name: aquascan-hmpi
    env: python
    buildCommand: cd AquaScan_prototype && npm install && npm run build && cd ..
    startCommand: gunicorn app:app
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000

